name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Azione di checkout più esplicita
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: '.' # Forza il checkout nella directory corrente

    - name: List files after checkout
      run: ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore AthenaGateway.sln

    - name: Build
      run: dotnet build AthenaGateway.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test AthenaGateway.sln --no-build --verbosity normal
